name: CI
on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |  
          sudo apt-get update
          sudo apt-get install -y g++ cmake python3
      
      - name : Build project
        run: |
          bash install.sh

      - name : Test project
        run: |
          cd build
          ./tests/testing